import { AppText, Badge, PageHeader, Screen, Surface } from '../components/ui';
import { colors } from '../theme';
export default function HowItWorks() {
  return <Screen><PageHeader back title="A promise worth keeping." eyebrow="How it works" />
    <Surface style={{ gap: 12, marginBottom: 20 }}><Badge label="Solo" /><AppText variant="title">Your pace. Your promise.</AppText><AppText>Choose your daily step goal, how many days you want to hit it, and deposit $5, $10, or $20. Your challenge starts immediately.</AppText><AppText>Every day you reach your step goal counts. Missed days never count against you — the challenge stays open until you complete all of them, however long that takes.</AppText><AppText color={colors.muted}>Example: a $10 deposit on 10,000 steps for 15 days. Finish those 15 goal days in 15 days or in 20 — either way the full $10 comes back only once all 15 are done. End the challenge early and the deposit goes to charity.</AppText></Surface>
    <Surface style={{ gap: 12, marginBottom: 20 }}><Badge label="Party" /><AppText variant="title">A little farther, together.</AppText><AppText>Everyone pledges the same amount toward the same daily step goal and duration. Share your invite code; the host starts once at least one friend joins.</AppText><AppText>Each person who completes all their days gets their full pledge back. When the challenge ends, every unfinished pledge goes to charity.</AppText><AppText color={colors.muted}>Example: four $5 pledges create a $20 pot. If three people finish their days, they each receive $5 back and the remaining $5 goes to charity.</AppText></Surface>
    <Surface style={{ gap: 12 }}><Badge label="Hackathon preview" tone="peach" /><AppText>Accounts, invites, progress and results sync through the local server. Keep your phones and the computer running Docker on the same Wi-Fi.</AppText><AppText>Real walk verification is coming soon. Use Simulate a completed day to test progress. Hosts can end a challenge early after confirming.</AppText><AppText>No actual payment is collected or charity donation transferred. Money and activity are simulated.</AppText></Surface>
  </Screen>;
}
